"type: documentation":
  - changed-files:
    - any-glob-to-any-file: ['**/docs/**', 'README.md', 'CHANGELOG.md']

"type: ci-cd":
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**']

"type: tests":
  - changed-files:
    - any-glob-to-any-file: ['**/tests/**']
