// Copyright (c) - Graphical Playground. All rights reserved.
// For more information, see https://graphical-playground/legal
// mailto:support AT graphical-playground DOT com

export const Constants = {
  name: 'Graphical Playground',
  description:
    'An interactive, browser-based platform where students deconstruct and rebuild graphics-engine systems from the ground up, from raw Vulkan commands to full render pipelines. Explore creative coding, canvas experiments, and real-time graphics programming.',
  product: (name: string) => `Graphical Playground ${name}`,
  alternateNames: ['GP', 'GPlayd', 'Graphical Playground'],
  keywords: [
    'Education',
    'E-Learning',
    'Graphics Programming',
    'Computer Graphics',
    'Graphics Engine',
    'Graphics Engineering',
    'Creative Coding',
    '3D Rendering',
    '2D Rendering',
    'Real-time Rendering',
    'Ray Tracing',
    'Rasterization',
    'Shaders',
    'Live Coding',
    'Interactive Coding',
    'Visual Programming',
    'Rapid Prototyping',
    'Data Visualization',
    'Vulkan',
    'WebGPU',
    'WebGL',
    'OpenGL',
    'OpenGLES',
    'DirectX',
    'DirectX 11',
    'DirectX 12 Ultimate',
    'DirectX 12',
    'Metal',
    'AGC',
    'Advanced Graphics Compiler',
    'GNM',
    'GNMX',
    'NVN',
    'Render Hardware Interface',
    'RHI',
    'Low-Level Graphics API',
    'Low-Level Graphics Programming',
    'Hardware Abstraction Layer',
    'HAL',
    'Game Development',
    'Computational Geometry',
    'Mathematics for Graphics',
    'Physics for Graphics',
    'Computer Science',
    'Software Engineering',
    'Learn Graphics Programming',
    'Learn Game Development',
    'Learn Computer Graphics',
    'Learn Engine Architecture',
    'Learn OpenGL',
    'Learn Vulkan',
    'Learn DirectX',
    'Learn Metal'
  ]
} as const;
