---
name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Use Node.js 26.x
        uses: actions/setup-node@v7
        with:
          node-version: '26.x'

      # TODO: Add build steps here
